### PR TITLE
Handle error scenarios gracefully in NodeUnpublishVolume

### PR DESCRIPTION
**Pull request by swamibluedata**
This fixes

https://github.com/spiffe/spiffe-csi/issues/158

Issue unmount if and only if the target folder is present and is a valid mount point.

Issue Remove call if and only if the target folder exists

If the mount point doesn't exist, report success, which will allow kubelet to continue with pod termination sequence

```
Signed-off-by: Swami Viswanathan <swami.viswanathan@hpe.com>
```

### CODE REVIEW

**Comment by swamibluedata** [comment]
Addressed a PR comment from the closed PR 

https://github.com/spiffe/spiffe-csi/pull/160

**Comment by azdagron** [comment]
Hey @swamibluedata! Thanks for this contribution! If you could fix the DCO on your commit, that would be great. You can click on the "details" link to the right of the failed action.

In your case it looks like the Signed-off-by is set to one email, but the author of the commit is another. You may need to do a `git commit --amend -s --reset-author` to fix the commit before force pushing.

**Comment by azdagron** [comment]
Looks like at least one unit test is also failing and may need to be updated based on the new behavior.

The failing integration test is unrelated (the v1.21.14 test is failing across the board at the moment).

**Comment by swamibluedata** [comment]
> Hey @swamibluedata! Thanks for this contribution! If you could fix the DCO on your commit, that would be great. You can click on the "details" link to the right of the failed action.
> 
> In your case it looks like the Signed-off-by is set to one email, but the author of the commit is another. You may need to do a `git commit --amend -s --reset-author` to fix the commit before force pushing.

Got it and will need to address the test case as well.

**Comment by swamibluedata** [comment]
> Looks like at least one unit test is also failing and may need to be updated based on the new behavior.
> 
> The failing integration test is unrelated (the v1.21.14 test is failing across the board at the moment).

Both the new "unable to verify mount point" error and an existing error "unable to unmount" are going to be tricky to test.

For "unable to verify mount point", i need to make enumerateMounts fail
For "unable to mount", i can run a process that opens a file on that mountpoint which will prevent unmount

Thinking

**Comment by azdagron** [comment]
The unit tests for the driver package replace the various functions with those where they can inject different conditions. That's probably good enough for the unit tests. At some point we'll wire up more test cases into the integration test, which is running in a kind cluster, but for now I think unit test coverage give us the same test fidelity we have now.

**Comment by swamibluedata** [comment]
> Hey @swamibluedata! Thanks for this contribution! If you could fix the DCO on your commit, that would be great. You can click on the "details" link to the right of the failed action.
> 
> In your case it looks like the Signed-off-by is set to one email, but the author of the commit is another. You may need to do a `git commit --amend -s --reset-author` to fix the commit before force pushing.

Updated the commit, still complaining :(

https://github.com/spiffe/spiffe-csi/pull/161/commits/37bb8fa045048021611a2362cdd1dd0c33162e28

**Comment by azdagron** [comment]
Looks like the last thing to fix is a linting error. You need to run goimports on one of the files you edited (setting up your editor to do this automatically when saving is usually the easiest path).

**Comment by swamibluedata** [comment]
@azdagron anything i need to address

**Review by azdagron — APPROVED** [review]
Thanks, @swamibluedata! Good to go.

**Pull request merged**
