### PR TITLE
feat(ci): run PR testing against a list of kubernetes versions

### PR DESCRIPTION
**Pull request by blairdrummond**
This adds a [matrix build](https://docs.github.com/en/actions/using-workflows/advanced-workflow-features#using-a-build-matrix) with a few of the recent kubernetes versions [supported by kind](https://hub.docker.com/r/kindest/node/tags). I noticed mention of the desire for this feature in this issue https://github.com/spiffe/spiffe-csi/issues/4 .

Screenshots:

Screenshot 2022-01-18 at 17-50-47 feat(ci) add testing for multiple k8s versions · blairdrummond spiffe-csi ce6eb6c

Screenshot 2022-01-18 at 17-55-22 feat(ci) add testing for multiple k8s versions · blairdrummond spiffe-csi ce6eb6c

### CODE REVIEW

**Comment by azdagron** [comment]
Awesome, this would be great! I notice some build failures in your screenshot. I've just enabled the CI/CD run so we'll find out in a second what they are :)

**Comment by azdagron** [comment]
Also, heads up, all contributions to the SPIFFE org must have DCO signoff on the commits (git commit -s)

**Comment by blairdrummond** [comment]
Signed off!

**Comment by blairdrummond** [comment]
Anything needed on my end?

**Comment by azdagron** [comment]
The tests for 1.18, 1.19, and 1.20 are failing to create the cluster. We need to figure out why.

**Comment by azdagron** [comment]
Thanks for kicking this off @blairdrummond! Sorry it took so long to get it in. Thanks for the contribution!

**Pull request merged**
