### PR TITLE
Move to pre-production maturity

### PR DESCRIPTION
**Pull request by azdagron**
This PR upgrades the [maturity](https://github.com/spiffe/spiffe/blob/main/MATURITY.md) level of the project from [Development](https://github.com/spiffe/spiffe/blob/main/MATURITY.md#development) to [Pre-Production](https://github.com/spiffe/spiffe/blob/main/MATURITY.md#pre-production-).

@spiffe/ssc, I'm not quite sure what the process is to promote a project maturity level or if it needs SSC involvement. I've reviewed the checklist at the above link and _think_ we've checked all the boxes. There is a simple integration test as well as unit tests for the [driver](pkg/driver) package, which contains the majority of the business logic. The weakest assertion is that the project is supported by early adopters. I don't know of many and getting early adopters without being at pre-prod feels a little like a chicken-and-egg problem... nevertheless I have had many folks reach out about the availability and stability of this component (e.g. #7).

I'd really appreciate some guidance!

### CODE REVIEW

**Comment by evan2645** [comment]
I took a look and it does seem to meet the bar, it would be great to hear a little more about your experience going through this process on the ssc call tomorrow!

+1 from my point of view, but I suspect we probably want some others to have a look too?

**Comment by azdagron** [comment]
>  it would be great to hear a little more about your experience going through this process on the ssc call tomorrow!

I'd be happy to share!

**Review by anvega — APPROVED** [review]
Examining the repo, it meets all characteristics of software in the pre-production phase as established in spiffe/MATURITY.md:

Apache 2 licensed ✅
Moderate velocity (weeks-to-month)✅
Best effort compatibility guarantee ✅
A comprehensive set of examples is available ✅
Automated test suites are exercised regularly ✅
Pre-built artifacts are published and made publicly available ✅
Supported by both developers and early adopter community ✅
A security policy is clearly defined ✅

Software has been fully documented and includes:

A clear indication that it is in the Pre-Production phase ✅
Supported versions of relevant components (e.g. supported SPIRE versions, etc) ✅
Known limitations ✅
Basic troubleshooting ✅
API documentation ✅

**Comment by azdagron** [comment]
Thanks for looking, folks!

**Pull request merged**
